default: &default
  secret_key_base: "test"  # only for test/dev

development:
  <<: *default

test:
  <<: *default

staging:
  server_name: ""
  <<: *default

production: &production
  secret_key_base: "<%= ENV["SECRET_KEY_BASE"] %>"

  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""

  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

  http_basic_auth: "<%= ENV["HTTP_BASIC_AUTH"] %>"
  http_basic_username: "<%= ENV["HTTP_BASIC_USERNAME"] %>"
  http_basic_password: "<%= ENV["HTTP_BASIC_PASSWORD"] %>"

  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""

  translate_username: ""
  translate_password:  ""

  rollbar_server_token: ""
  server_name: "<%= ENV["SERVER_NAME"] %>"

preproduction:
  server_name: ""
  <<: *production
